[logger]
level = "INFO"
filePath = ""

[storage]
type = "sql" # или "in-memory"

[database]
host = "localhost"
port = 5432
user = "calendar"
pwd = "calendar"
dbname = "calendar"

[http]
host = "0.0.0.0"
port = 8080
